### ISSUE TITLE
Homework 6 Feedback 

### ISSUE THREAD

**Issue by lwdozal** [INFO526-DataViz/hw-06-meganhokama#2]
Dear [meganhokama] -- Below is the feedback for your assignment. Please review carefully, and stop by office hours if you have any questions about the feedback.

Score: 94/100
---

### Exercise 1: `[17 / 20 points]`

- Data loading w/ `skip`: `[5 / 5]`
- Summarising: `[5 / 5]`
- Animating racing bar chart: `[7 / 10]`
- Feedback: [Your y-axis font is very small, and the data labels don't have commas and are moving too quickly to understand the amount. It might be better to have population numbers on the x-axis. ]

### Exercise 2: `[10 / 10 points]`

  - Data wrangling: `[5 / 5]`
  - Final dataset: `[5 / 5]`

### Exercise 3: `[18 / 20 points]`

  - Data wrangling: `[5 / 5]`
  - New plot: `[4 / 5]`
  - Accessibility best practices: `[4 / 5]`
  - Narrative: `[5 / 5]`
  - Feedback: [Although the categories aren't overlapping, the colors of the countries are very similar making it somewhat hard to discern. I'm also not sure what frequency means here.]
  
### Exercise 4: `[10 / 10 points]`

- App code: `[5 / 5 points]`
- Active link on shiny.io: `[5 / 5 points]`
- Correct file organization: `[5 / 5 points]`
- Feedback: [Insert feedback here.]

### Exercise 5: `[14 / 15 points]`
- App code: `[5 / 5 points]`
- New stylizing: `[4 / 5 points]`
- Active link on shiny.io: `[5 / 5 points]`
- Correct file organization: `[5 / 5 points]`
Feedback: [the x-axis font is small and there are interesting font choices.]

### Overall: `[20 / 20 points]`

- `[5 / 5]` - Doesn't require reproduction: .md file is in repo, figures show up in the .md file on GitHub, no egregious errors requiring reproducing the entire analysis to be able to follow it.
- `[3 / 3]` - Code style: Line breaks after `|>` and `+`, spaces around operators, spaces after commas, lines not too long, etc.
- `[3 / 3]` - Code smell: Messy / unnecessarily complex code, difficult to follow, unaddressed warnings, etc.
- `[3 / 3]` - Quality and quantity of commits: No uninformative/nonsense text in commit messages, entire assignment not committed in a single commit.
- `[3 / 3]` - Reasonably sized figures.
- `[3 / 3]` - Font size, organization: No crazy large text for narrative, questions answered in order and identified, easy to follow.

## Late penalty

- [ ] On time: No penalty
- [ ] Late, but same day (before midnight): -10 points
- [ ] Late, but next day: -20 points

**Comment by meganhokama** [comment]
Thank you for the feedback!
